name: Deploy vers OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Envoyer le site vers OVH
        uses: Dylan700/sftp-upload-action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          uploads: |
          uploads: |
  ./ => ./www/
          ignore: |
            .git/**
            .github/**
            README.md
          delete: false
